# Server Port
server.port=9090

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://db:5432/shareit
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=shareit
spring.datasource.password=shareit

# JPA for PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# SQL initialization
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

# Logging
logging.level.ru.practicum.shareit=DEBUG